package com.example.CashFlowControlBackEnd.Exceptions.Enums;

public enum GenericExceptionKey {

    //Category
    CATEGORY_ID_IS_REQUIRED,
    CATEGORY_ID_NOT_FOUND,
    CATEGORY_NAME_IS_REQUIRED,
    CATEGORY_NAME_ALREADY_EXISTS,
    CATEGORY_NOT_FOUND,

    //Transaction
    INVALID_TRANSACTION_AMOUNT,
    TRANSACTION_DATE_IS_REQUIRED,
    TRANSACTION_TYPE_IS_REQUIRED,
    TRANSACTION_ID_IS_REQUIRED,
    TRANSACTION_ID_NOT_FOUND,
    TRANSACTION_NOT_FOUND;
}
